<a href="https://colab.research.google.com/github/himesh992/ML-project/blob/main/email_spam_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from nltk.corpus import stopwords
import string

In [ ]:
from google.colab import files; upload = files.upload()

Saving emails.csv to emails.csv


In [ ]:
df = pd.read_csv('emails.csv')

In [ ]:
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [ ]:
df.shape

(5728, 2)

In [ ]:
df.columns

Index(['text', 'spam'], dtype='object')

In [ ]:
#check for duplicates and remove them
df.drop_duplicates(inplace = True)

In [ ]:
df.shape

(5695, 2)

In [ ]:
#show the number of missing data for each column
df.isnull().sum()

text    0
spam    0
dtype: int64

In [ ]:
#download the stopword package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
def process_text(text):
  #remove punctuation
  #remove stopwords
  #return a list of clean text words

  nopunc = [char for char in text if char not in string.punctuation]
  nopunc = ''.join(nopunc)

  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

  return clean_words

In [ ]:
#show tokenization( a list of tokens also called lemmas)
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [ ]:
#example
message4= 'hello world hello hello world play'
message5 = 'test test test test one hello'
print(message4)
print()

#Convert the text to a matrix of token counts
from sklearn.feature_extraction.text import CountVectorizer
bow4 = CountVectorizer(analyzer = process_text).fit_transform([message4], [message5])

print(bow4)
print()
print(bow4.shape)

hello world hello hello world play

  (0, 0)	3
  (0, 2)	2
  (0, 1)	1

(1, 3)


In [ ]:
#Convert a collection of text to a matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
message_bow = CountVectorizer(analyzer = process_text).fit_transform(df['text'])


In [ ]:
#split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(message_bow, df['spam'], test_size = 0.20, random_state = 0)

In [ ]:
#get the shape of messages bow
message_bow.shape

(5728, 37229)

In [ ]:
#create and train the naives bayes classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train, y_train)

In [ ]:
#print the predictions
print(classifier.predict(X_train))

#print the actual values
print(y_train.values)


[0 0 1 ... 0 0 0]
[0 0 1 ... 0 0 0]


In [ ]:
#evaluate the model on the testing data
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(y_train, pred))
print()
print('Confusion Matrix:  \n ', confusion_matrix(y_train, pred))
print()
print('Accuracy: ',  accuracy_score(y_train, pred))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3475
           1       0.99      1.00      1.00      1107

    accuracy                           1.00      4582
   macro avg       1.00      1.00      1.00      4582
weighted avg       1.00      1.00      1.00      4582


Confusion Matrix:  
  [[3466    9]
 [   2 1105]]

Accuracy:  0.9975993016150153
